spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: movie-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/movies/**
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

