spring: 
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/.well-known/openid-configuration

  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/booking_service_db;DB_CLOSE_DELAY=-1
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

movie:
  service:
    base-url: http://localhost:8082
