server:
  port: 8083

spring: 
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/booking_service_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: your-very-secret-key-123456789012

movie:
  service:
    base-url: http://localhost:8080   # movie-service port (or gateway later)
payment:
  service:
    base-url: http://localhost:8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
          prefer-ip-address: true
          hostname: localhost

redis:
  url: redis://127.0.0.1:6379   # 👈 now at root level

booking:
  hold-ttl-minutes: 5
  lock-wait-seconds: 2
