spring :
    application :
        name : payment-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true
server : 
    port : 8084

#redis:
#      url: redis://127.0.0.1:6379 
