spring: 
  cache: 
    type: redis

  application:
    name: movie-service

  datasource: 
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/movie_service_db

  jpa: 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis: 
      port: 6379
      host: localhost
server:
  port: 8082

jwt: 
  secret: "your-very-secret-key-123456789012"

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
    register-with-eureka: true