spring: 

  application:
    name: movie-service

  datasource: 
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/movie_service_db

  jpa: 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8082

jwt: 
  secret: "your-very-secret-key-123456789012"